// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI needs a URL string at generate/build time.
    // In some CI/preview environments DATABASE_URL isn't provided until runtime;
    // use a harmless local fallback so `prisma generate` can still succeed.
    url:
      process.env["DATABASE_URL"] ??
      "postgresql://postgres:postgres@localhost:5432/postgres?schema=public",
  },
});
